### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by avouros** [RodentDataAnalytics/mwm-ml-gen#1]
**OS:** Mac (retina display)
**Software:** Matlab 2015a, 2016a
**Action:** Running the 'gui' command to load the main graphical user interface.

While everything works fine when running the GUI under MATLAB ver. 2015a, it doesn’t work on 2016a. I also had the same issue on another machine (Mac, retina display, Matlab 2015b and 2016b).

Suggestions:
Maybe a Mac only issue, retina display only issue or Matlab version depending issue (maybe runs only with versions<2015b).

Matlab r2015a:
<img width="723" alt="matlab r2015a" src="https://cloud.githubusercontent.com/assets/11095133/15600659/3edcb022-23e3-11e6-94b7-4fd540fff275.png">

Matlab r2016a:
<img width="1121" alt="matlab r2016a" src="https://cloud.githubusercontent.com/assets/11095133/15600656/38b4943a-23e3-11e6-9ea0-1dee086a4ae1.png">

**Comment by mikecroucher** [comment]
Confirmed with a Retina Macbook Pro and the following MATLAB versions

* 2014a - gui.m works fine
* 2015a - gui.m works fine
* 2016a - gui.m is corrupted, as displayed above

**Comment by mikecroucher** [comment]
The changes seem to have come in at 2015b 

http://uk.mathworks.com/help/matlab/creating_guis/dpi-aware-behavior-in-matlab.html

This may be relevant
http://uk.mathworks.com/help/matlab/creating_guis/designing-for-cross-platform-compatibility.html#f8-1028670

**Comment by mikecroucher** [comment]
MATLAB 'ver' information for 2016a -- the version that fails

```
>> ver
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.0.0.341360 (R2016a)
MATLAB License Number: 976008
Operating System: Mac OS X  Version: 10.11.2 Build: 15C50 
Java Version: Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.0         (R2016a)
Curve Fitting Toolbox                                 Version 3.5.3       (R2016a)
Global Optimization Toolbox                           Version 3.4         (R2016a)
Image Acquisition Toolbox                             Version 5.0         (R2016a)
Image Processing Toolbox                              Version 9.4         (R2016a)
MATLAB Coder                                          Version 3.1         (R2016a)
Optimization Toolbox                                  Version 7.4         (R2016a)
Parallel Computing Toolbox                            Version 6.8         (R2016a)
Statistics and Machine Learning Toolbox               Version 10.2        (R2016a)
Symbolic Math Toolbox                                 Version 7.0         (R2016a)
```

**Comment by avouros** [comment]
**Update:**
In order for the GUI to run on any machine correctly:
- *Font:* points
- *Units:* characters

**Issue:** 
Sometimes loading the GUI in MAC the *units* take the value of *normalized* which corrupts the appearance of the interface.

Also, loading the GUI in MATLAB versions 2014 and lower the *units* take the value of *pixels*.

**Solution (under testing):**
To overcome this issue we should make sure that the GUI is saved under MATLAB versions 2015b and upper with font=points and *units=characters* (loading the code in MATLAB 2014 and lower may automatically re-save it with *units=points*). In this way running it on any machine or MATLAB version it will appear as it supposed to be.

**Comment by mikecroucher** [comment]
Mathworks tech support sent me this

There are several workarounds that you could try:

1) Change all 'characters' units to 'pixels'. This code may help:
 
```
hFig = openfig('GUIName');
hAllObj = findobj(hFig);
for k = 1:numel(hAllObj)
    try
        if strcmp(hAllObj(k).Units,'characters')
            hAllObj(k).Units = 'pixels';
        end
    catch me
        disp(me.message)
    end
end
savefig(hFig,'GUIName')
```
 
2) Change all units to 'normalized'. This can be done similarly to the above workaround, or just open the GUI in GUIDE, go to Tools -> GUI Options -> Resize Behavior, and change that to "Proportional". This also prevents MATLAB from resizing the figure window to fit on one screen, although Windows may still impose limits on the size of the figure window.
 
3) Make all of the units 'characters' and accept the change. Everything should increase in size proportionally, so the only issue should be if the GUI becomes too large for the screen.

**Comment by avouros** [comment]
Fixed by using:
Resize behavior = Proportional
Units = Normalized

**Disadvantage:** https://github.com/RodentDataAnalytics/mwm-ml-gen/issues/13

**Comment by avouros** [comment]
Final GUI proposition (mac & win):

Resize behavior = Proportional
Units = Normalized
Font = Arial (points)

![mac_gui](https://cloud.githubusercontent.com/assets/11095133/15864600/9cab8f30-2ccf-11e6-8638-68898800b38e.png)

![win_gui](https://cloud.githubusercontent.com/assets/11095133/15864604/9f92873a-2ccf-11e6-8a76-e7a38bf387c2.png)

Some texts may not appear correctly due to the size of the screen but everything can be fixed upon resizing the window.
